"""
Django settings for zhada_talk_backend project.

Generated by 'django-admin startproject' using Django 5.2.x.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------- Media / Static ----------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = 'static/'

# ---------- Security / Basic ----------
# SECURITY WARNING: keep the secret key used in production secret!
# In production, load this from an environment variable or vault
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-&r5g8#+*d%%*hn(=bljb5rjsm3mnn-0rt3tc#(y=#8^_&*d*#9')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if os.environ.get('DJANGO_ALLOWED_HOSTS') else []


# ---------- Installed apps ----------
INSTALLED_APPS = [
    # django built-ins
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_yasg',                # swagger if you use it
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # add social providers you need, e.g. 'allauth.socialaccount.providers.google'
    'axes',                    # django-axes for brute-force protection

    # your apps
    'accounts',
    'follows',
    'wallets',
]

# required by allauth
SITE_ID = int(os.environ.get('DJANGO_SITE_ID', 1))


# ---------- Middleware ----------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # cors should come before CommonMiddleware and AuthenticationMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',

    # Axes middleware should be before AuthenticationMiddleware
    'axes.middleware.AxesMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # allauth account middleware can remain (optional)
    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zhada_talk_backend.urls'

# ---------- Templates ----------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # add templates dirs if needed
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zhada_talk_backend.wsgi.application'


# ---------- Database ----------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'zhada_talk_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'Aben4321##'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# ---------- Password validation ----------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ---------- Internationalization ----------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------- Email (production: use env vars / secret manager) ----------
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get('EMAIL_HOST', "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', "avelox6867@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', "sgsk skkh sqkn qnpa")  # store securely in prod

# ---------- Custom user model ----------
AUTH_USER_MODEL = 'accounts.User'


# ---------- Authentication backends ----------
AUTHENTICATION_BACKENDS = (
    'axes.backends.AxesBackend',                           # axes first
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


# ---------- Allauth settings ----------

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True                  # Email is mandatory
ACCOUNT_USERNAME_REQUIRED = False             # No username field
ACCOUNT_AUTHENTICATION_METHOD = 'email'       # Login via email only
ACCOUNT_SIGNUP_FIELDS = ['email', 'password1', 'password2', 'first_name', 'last_name']

# Email verification settings
ACCOUNT_EMAIL_VERIFICATION = os.environ.get('ACCOUNT_EMAIL_VERIFICATION', 'optional')  # 'mandatory' in prod

# Redirect URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# ---------- Social providers (example Google) ----------
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    }
}


# ---------- Axes (django-axes) ----------
# Use integer for env, or parse into timedelta in more advanced setups
AXES_FAILURE_LIMIT = int(os.environ.get('AXES_FAILURE_LIMIT', 5))
# COOL_OFF time in hours by default here; convert to timedelta for robustness
from datetime import timedelta as _td
AXES_COOLOFF_TIME = _td(hours=int(os.environ.get('AXES_COOLOFF_TIME_HOURS', 1)))
AXES_ONLY_USER_FAILURES = False
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_USE_USER_AGENT = True
AXES_RESET_ON_SUCCESS = True  # reset failure count on successful login


# ---------- REST Framework & Throttling ----------
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),

    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),

    # Global throttles (fallback). Use scoped throttles in views for fine-grained control.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),

     'DEFAULT_THROTTLE_RATES': {
        'anon': '10/min',       # global unauthenticated
        'user': '60/min',       # global authenticated
        'login': '5/min',       # login endpoint only
        'register': '3/min',    # registration endpoint only
        'password_reset': '3/min',  # password reset
        'dj_rest_auth': '10/minute', 
    },
}


# ---------- SimpleJWT ----------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_MINUTES', 15))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', 7))),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    # customize algorithm, signing key etc in production
}

# Make dj-rest-auth use JWT
REST_USE_JWT = True


# ---------- dj-rest-auth / allauth overrides (serializers) ----------
# Point these to serializers you will create in accounts.serializers
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
}

REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.CustomUserSerializer',
    # 'LOGIN_SERIALIZER': 'accounts.serializers.CustomLoginSerializer',  # optional
}


# ---------- CORS ----------
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL', 'True') == 'True'
# For production, set CORS_ALLOWED_ORIGINS to a list of allowed origins instead


# ---------- Logging (basic, includes axes logger) ----------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'axes': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}


# ---------- Allauth email / confirmation settings (example) ----------
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
EMAIL_CONFIRMATION_EXPIRE_DAYS = int(os.environ.get('EMAIL_CONFIRMATION_EXPIRE_DAYS', 3))


# ---------- Misc / Utility ----------
# Add any other settings you need here (e.g., Redis for Celery, caching, etc.)

# ---------- Example: DRF Simple JWT token blacklist migration note ----------
# Make sure to run:
#   python manage.py makemigrations
#   python manage.py migrate
# after adding 'rest_framework_simplejwt.token_blacklist' to INSTALLED_APPS

